modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved, (c) Davidutz 2023"
[[mods]]
modId="floppadventuremod"
version="1.0.0"
displayName="FloppAdventure Mod"
logoFile="icon.png"
credits="Davidutz & Retrix_Off"
authors="Davidutz for development, Retrix_Off for textures"

description='''
FloppAdventure Mod, Official mod for FloppAdventure server
'''